dist: bionic
language: java
jdk:
  - oraclejdk11

script:
  - ./gradlew test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/