version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    environment:
      KAFKA_CREATE_TOPICS: "intake.stockt.request:1:1,intake.stockt.acknowledgement:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: localhost # docker machine ip
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
    ports:
      - "9092:9092"

  postgresql:
    build:
      context: docker/postgresql
    environment:
      POSTGRES_STOCKT_USERNAME: stockt_user
      POSTGRES_STOCKT_PASSWORD: password
      POSTGRES_STOCKT_DATABASE: stockt
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"