#!/bin/bash

set -e
set -u

echo "Creating user: $POSTGRES_STOCKT_USERNAME"
echo "Creating database: $POSTGRES_STOCKT_DATABASE"

psql -v ON_ERROR_STOP=1 --user "$POSTGRES_USER" -e "$POSTGRES_PASSWORD" <<-EOSQL
  CREATE USER $POSTGRES_STOCKT_USERNAME WITH PASSWORD '$POSTGRES_STOCKT_PASSWORD';
  CREATE DATABASE $POSTGRES_STOCKT_DATABASE;
  GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_STOCKT_DATABASE to $POSTGRES_STOCKT_USERNAME;
  ALTER DATABASE $POSTGRES_STOCKT_DATABASE OWNER TO $POSTGRES_STOCKT_USERNAME;
  ALTER ROLE $POSTGRES_STOCKT_USERNAME WITH CREATEROLE;
  ALTER ROLE $POSTGRES_STOCKT_USERNAME WITH SUPERUSER;
EOSQL

psql -d "$POSTGRES_STOCKT_DATABASE" -U "$POSTGRES_STOCKT_USERNAME" -a -f /tmp/sql/stockt.sql